SET DEFINE OFF;
CREATE OR REPLACE TRIGGER NEW_APDEV.INSERT_P02_IS_DATA_COLLECT
    AFTER INSERT ON NEW_APDEV.DC_P02_IS
    REFERENCING NEW AS NEW_DC_P02_IS
    FOR EACH ROW
BEGIN
        INSERT INTO DATA_COLLECT_RECORDS
        SELECT
        :NEW_DC_P02_IS.DATE_ENTERED,
        RTRIM(:NEW_DC_P02_IS.POLICY_NUMBER),
        (
        :NEW_DC_P02_IS.STATUS ||
        :NEW_DC_P02_IS.TRANSACTION_TYPE ||
    :NEW_DC_P02_IS.POLICY_NUMBER ||
:NEW_DC_P02_IS.HISTORY_CODE ||
:NEW_DC_P02_IS.ITEM_NUMBER ||
:NEW_DC_P02_IS.MAP_NAME ||
:NEW_DC_P02_IS.RECORD_NUMBER ||
:NEW_DC_P02_IS.FILLER_0025_0030 ||
:NEW_DC_P02_IS.POL_NO ||
:NEW_DC_P02_IS.ACTION_1 ||
:NEW_DC_P02_IS.SEQ_1 ||
:NEW_DC_P02_IS.N_A_1 ||
:NEW_DC_P02_IS.STREET_1 ||
:NEW_DC_P02_IS.CITY_1 ||
:NEW_DC_P02_IS.STATE_1 ||
:NEW_DC_P02_IS.ZIP_1 ||
:NEW_DC_P02_IS.ACTION_2 ||
:NEW_DC_P02_IS.SEQ_2 ||
:NEW_DC_P02_IS.NAME_2 ||
:NEW_DC_P02_IS.N_A_2 ||
:NEW_DC_P02_IS.STREET_2 ||
:NEW_DC_P02_IS.CITY_2 ||
:NEW_DC_P02_IS.STATE_2 ||
:NEW_DC_P02_IS.ZIP_2 ||
:NEW_DC_P02_IS.LOAN_NO_2 ||
:NEW_DC_P02_IS.ACTION_3 ||
:NEW_DC_P02_IS.SEQ_3 ||
:NEW_DC_P02_IS.NAME_3 ||
:NEW_DC_P02_IS.N_A_3 ||
:NEW_DC_P02_IS.STREET_3 ||
:NEW_DC_P02_IS.CITY_3 ||
:NEW_DC_P02_IS.STATE_3 ||
:NEW_DC_P02_IS.ZIP_3 ||
:NEW_DC_P02_IS.INT_3 ||
:NEW_DC_P02_IS.ACTION_4 ||
:NEW_DC_P02_IS.SEQ_4 ||
:NEW_DC_P02_IS.NAME_4 ||
:NEW_DC_P02_IS.NM_TYP_4 ||
:NEW_DC_P02_IS.N_A_4 ||
:NEW_DC_P02_IS.STREET_4 ||
:NEW_DC_P02_IS.CITY_4 ||
:NEW_DC_P02_IS.STATE_4 ||
:NEW_DC_P02_IS.ZIP_4 ||
:NEW_DC_P02_IS.DESC_CODE ||
:NEW_DC_P02_IS.NM_ALIAS_LST ||
:NEW_DC_P02_IS.NM_ALIAS_FST ||
:NEW_DC_P02_IS.RES_TERR ||
:NEW_DC_P02_IS.USE_OF_B28_1 ||
:NEW_DC_P02_IS.USE_OF_B28_2 ||
:NEW_DC_P02_IS.USE_OF_B28_3 ||
:NEW_DC_P02_IS.USE_OF_B28_4 ||
:NEW_DC_P02_IS.ALTERNATE_2 ||
:NEW_DC_P02_IS.ALTERNATE_4 ||
:NEW_DC_P02_IS.INS_SOC_SEC ||
:NEW_DC_P02_IS.INS_FEIN_CODE ||
:NEW_DC_P02_IS.INS_SCORE ||
:NEW_DC_P02_IS.INS_RC01 ||
:NEW_DC_P02_IS.INS_RC02 ||
:NEW_DC_P02_IS.INS_RC03 ||
:NEW_DC_P02_IS.INS_RC04 ||
:NEW_DC_P02_IS.INS_SCR_DATE ||
:NEW_DC_P02_IS.SOC_SEC ||
:NEW_DC_P02_IS.LOSS_PAYEE_TYPE ||
:NEW_DC_P02_IS.FILLER_0678_1000

        )
        from dual;

END INSERT_P02_IS_DATA_COLLECT;
/
