SET DEFINE OFF;
CREATE OR REPLACE TRIGGER NEW_APDEV.INSERT_P90_RENEWAL_2
    AFTER INSERT ON NEW_APDEV.DC_P90_RENEWAL_2
	REFERENCING NEW AS NEW_DC_P90_RENEWAL_2
    FOR EACH ROW
BEGIN
        INSERT INTO DATA_COLLECT_RECORDS
		SELECT
		:NEW_DC_P90_RENEWAL_2.DATE_ENTERED,
		RTRIM(:NEW_DC_P90_RENEWAL_2.POLICY_NUMBER),
		(
		 :NEW_DC_P90_RENEWAL_2.STATUS ||
		 :NEW_DC_P90_RENEWAL_2.TRANSACTION_TYPE ||
		 :NEW_DC_P90_RENEWAL_2.POLICY_NUMBER ||
		 :NEW_DC_P90_RENEWAL_2.FILLER_01 ||
		 :NEW_DC_P90_RENEWAL_2.ITEM_NUMBER || 
		 :NEW_DC_P90_RENEWAL_2.MAP_NAME ||
		 :NEW_DC_P90_RENEWAL_2.RECORD_NUMBER ||
		 :NEW_DC_P90_RENEWAL_2.FILLER_02 ||
		 :NEW_DC_P90_RENEWAL_2.POL_NO ||
		 :NEW_DC_P90_RENEWAL_2.CANCEL_MO ||
		 :NEW_DC_P90_RENEWAL_2.CANCEL_DAY ||
		 :NEW_DC_P90_RENEWAL_2.CANCEL_YR ||
		 :NEW_DC_P90_RENEWAL_2.CANCEL_REAS ||
		 :NEW_DC_P90_RENEWAL_2.CANCEL_PRO ||
		 :NEW_DC_P90_RENEWAL_2.CANCEL_SHRT ||
		 :NEW_DC_P90_RENEWAL_2.CO_CANC_AMT ||
		 :NEW_DC_P90_RENEWAL_2.REIN_MO ||
		 :NEW_DC_P90_RENEWAL_2.REIN_DAY ||
		 :NEW_DC_P90_RENEWAL_2.REIN_YR ||
		 :NEW_DC_P90_RENEWAL_2.REIN_REAS ||
		 :NEW_DC_P90_RENEWAL_2.REIN_TYPE ||
		 :NEW_DC_P90_RENEWAL_2.RENEW ||
		 :NEW_DC_P90_RENEWAL_2.DO_NOT_RENEW ||
		 :NEW_DC_P90_RENEWAL_2.REQ_WHO ||
		 :NEW_DC_P90_RENEWAL_2.REQ_REAS ||
		 :NEW_DC_P90_RENEWAL_2.EP_UNPAID_AMT ||
		 :NEW_DC_P90_RENEWAL_2.EP_UNPAID_CLR ||
		 :NEW_DC_P90_RENEWAL_2.PTC_IND ||
		 :NEW_DC_P90_RENEWAL_2.ACT_CODE_7 ||
		 :NEW_DC_P90_RENEWAL_2.ACT_DATE_7_MM ||
		 :NEW_DC_P90_RENEWAL_2.ACT_DATE_7_DD ||
		 :NEW_DC_P90_RENEWAL_2.ACT_DATE_7_YY ||
		 :NEW_DC_P90_RENEWAL_2.RECANCEL_IND ||
		 :NEW_DC_P90_RENEWAL_2.FILLER_03
		 )
		
		FROM DUAL;

END INSERT_P90_RENEWAL_2;
/
