SET DEFINE OFF;
CREATE OR REPLACE TRIGGER NEW_APDEV.INSERT_P01_DATA_COLLECT
AFTER INSERT
ON new_apdev.DC_P01
REFERENCING NEW AS NEW_DC_P01 OLD AS OLD
FOR EACH ROW
BEGIN
        INSERT INTO new_apdev.DATA_COLLECT_RECORDS
        SELECT
        :NEW_DC_P01.DATE_ENTERED,
        RTRIM(:NEW_DC_P01.POLICY_NUMBER),
        (
:NEW_DC_P01.STATUS ||
:NEW_DC_P01.TRANSACTION_TYPE ||
:NEW_DC_P01.POLICY_NUMBER ||
:NEW_DC_P01.HISTORY_CODE ||
:NEW_DC_P01.ITEM_NUMBER ||
:NEW_DC_P01.MAP_NAME ||
:NEW_DC_P01.RECORD_NUMBER ||
:NEW_DC_P01.FILLER_0025_0030 ||
:NEW_DC_P01.POL_NO ||
:NEW_DC_P01.CONV ||
:NEW_DC_P01.ORG_EF_DT ||
:NEW_DC_P01.OLD_POLNO ||
:NEW_DC_P01.LINE_CD ||
:NEW_DC_P01.POLICY_TYPE ||
:NEW_DC_P01.RENEWAL_TYPE ||
:NEW_DC_P01.CORR_NB ||
:NEW_DC_P01.CORR_REN ||
:NEW_DC_P01.TOWER_PAK ||
:NEW_DC_P01.NSF_CHECK_CNT ||
:NEW_DC_P01.SHORT_PAY ||
:NEW_DC_P01.RESUB_CSH ||
:NEW_DC_P01.PROC_CNTR ||
:NEW_DC_P01.SHORT_TERM ||
:NEW_DC_P01.NO_DT_CHK ||
:NEW_DC_P01.COMP_CD ||
:NEW_DC_P01.BRANCH ||
:NEW_DC_P01.AUDIT_RPT ||
:NEW_DC_P01.ASSUM_BUS ||
:NEW_DC_P01.ORIG_CO ||
:NEW_DC_P01.INQUIRY_TYPE ||
:NEW_DC_P01.DIVIDENT_AMT ||
:NEW_DC_P01.PICTURE ||
:NEW_DC_P01.ACCOMOD ||
:NEW_DC_P01.INST_NO ||
:NEW_DC_P01.TOT_INST ||
:NEW_DC_P01.REWRT_POL ||
:NEW_DC_P01.VIP_IND ||
:NEW_DC_P01.POL_FEE ||
:NEW_DC_P01.UWREF_CD5 ||
:NEW_DC_P01.UWREF_DT5 ||
:NEW_DC_P01.UWREF_CD6 ||
:NEW_DC_P01.UWREF_DT6 ||
:NEW_DC_P01.UWREF_CD7 ||
:NEW_DC_P01.UWREF_DT7 ||
:NEW_DC_P01.END1 ||
:NEW_DC_P01.END2 ||
:NEW_DC_P01.END3 ||
:NEW_DC_P01.END4 ||
:NEW_DC_P01.END5 ||
:NEW_DC_P01.END6 ||
:NEW_DC_P01.END7 ||
:NEW_DC_P01.END8 ||
:NEW_DC_P01.END9 ||
:NEW_DC_P01.END10 ||
:NEW_DC_P01.ACTION_1 ||
:NEW_DC_P01.ACTION_2 ||
:NEW_DC_P01.ACTION_3 ||
:NEW_DC_P01.ACTION_4 ||
:NEW_DC_P01.ACTION_5 ||
:NEW_DC_P01.ACTION_6 ||
:NEW_DC_P01.ACTION_7 ||
:NEW_DC_P01.ACTION_8 ||
:NEW_DC_P01.ACTION_9 ||
:NEW_DC_P01.ACTION_10 ||
:NEW_DC_P01.REINS_IND ||
:NEW_DC_P01.BACKDATE_CHG ||
:NEW_DC_P01.NO_DEC_IND ||
:NEW_DC_P01.AGINTER_CUST_ID ||
:NEW_DC_P01.CASE_NUM ||
:NEW_DC_P01.UND_ACCOUNT_ID ||
:NEW_DC_P01.LOWMIL_RET_DATE ||
:NEW_DC_P01.EXPERIENCE_RATED ||
:NEW_DC_P01.UWREF_CD3 ||
:NEW_DC_P01.UWREF_DT3 ||
:NEW_DC_P01.UWREF_CD4 ||
:NEW_DC_P01.UWREF_DT4 ||
:NEW_DC_P01.EXPERIENCE_LIAB ||
:NEW_DC_P01.EXPERIENCE_PD ||
:NEW_DC_P01.DROP_STAT_SW ||
:NEW_DC_P01.MCHANGE_OVERRIDE_IND ||
:NEW_DC_P01.SR22_SENT_CODE ||
:NEW_DC_P01.FILLER_02 ||
:NEW_DC_P01.END_ED_DATE_01 ||
:NEW_DC_P01.END_ED_DATE_02 ||
:NEW_DC_P01.END_ED_DATE_03 ||
:NEW_DC_P01.END_ED_DATE_04 ||
:NEW_DC_P01.END_ED_DATE_05 ||
:NEW_DC_P01.END_ED_DATE_06 ||
:NEW_DC_P01.END_ED_DATE_07 ||
:NEW_DC_P01.END_ED_DATE_08 ||
:NEW_DC_P01.END_ED_DATE_09 ||
:NEW_DC_P01.END_ED_DATE_10 ||
:NEW_DC_P01.COMPANION_INDICATOR ||
:NEW_DC_P01.FILLER_03 ||
:NEW_DC_P01.RFP_TOTAL ||
:NEW_DC_P01.EAF_TOTAL ||
:NEW_DC_P01.FILLER_04 ||
:NEW_DC_P01.EFT_DEP_IND ||
:NEW_DC_P01.FILLER_05
)
from DUAL;

end INSERT_P01_DATA_COLLECT;
/
