SET DEFINE OFF;
CREATE OR REPLACE TRIGGER NEW_APDEV.INSERT_P91_DATA_COLLECT
    AFTER INSERT ON NEW_APDEV.DC_PDC_91_CASH     REFERENCING NEW AS NEW_DC_IN_CASH
    FOR EACH ROW
BEGIN
        INSERT INTO DATA_COLLECT_RECORDS
        SELECT
       -- POLICY.GROUP_LINE_CODE,
        :NEW_DC_IN_CASH.DATE_ENTERED,--SYSDATE, -- swap out for production -> :NEW_DC_IN_CASH.DATE_ENTERED,
        RTRIM(:NEW_DC_IN_CASH.POL_NUM),
        (
        :NEW_DC_IN_CASH.STATUS ||
        :NEW_DC_IN_CASH.TRANSACTION_TYPE ||
        :NEW_DC_IN_CASH.CASH_KEY ||
        :NEW_DC_IN_CASH.HISTORY_CODE ||
        :NEW_DC_IN_CASH.ITEM_NUMBER ||
:NEW_DC_IN_CASH.MAP_NAME ||
:NEW_DC_IN_CASH.RECORD_NUMBER ||
:NEW_DC_IN_CASH.FILLER_0025_0030 ||
:NEW_DC_IN_CASH.BATCH_NUMBER ||
:NEW_DC_IN_CASH.BATCH_DATE ||
:NEW_DC_IN_CASH.BATCH_TOTAL ||
:NEW_DC_IN_CASH.PROC_CENTER ||
:NEW_DC_IN_CASH.POL_NUM ||
:NEW_DC_IN_CASH.INSURED_NAME ||
:NEW_DC_IN_CASH.CASH_AMOUNT ||
:NEW_DC_IN_CASH.PAY_OPTION ||
:NEW_DC_IN_CASH.REINSTATE ||
:NEW_DC_IN_CASH.SHORT_PAY ||
:NEW_DC_IN_CASH.RESUBMIT ||
:NEW_DC_IN_CASH.PROC_DATE ||
:NEW_DC_IN_CASH.PROC_BATCH_NUMBER ||
:NEW_DC_IN_CASH.PAID_BY ||
:NEW_DC_IN_CASH.NSF ||
:NEW_DC_IN_CASH.SVC_CHG ||
:NEW_DC_IN_CASH.FILLER_0110_0991
)
from NEW_APDEV.POLICY -- change to apdev for production
where RTRIM(:NEW_DC_IN_CASH.POL_NUM) = RTRIM(POLICY.POLICY_NUMBER);

END INSERT_P91_DATA_COLLECT;
/
