CREATE OR REPLACE PROCEDURE STAGING.LOAD_HISTORY_WANG_COVERAGE
IS
     
/***************************************************
***                                              ***
***   SHAYNES   10/18/2016                       ***
***   Procedure that will load the               ***
***  STAGING.HISTORY_WANG_COVERAGE_RECORD DAILY  *** 
***                                              ***
****************************************************/

   v_procname        VARCHAR2(40)                      := 'LOAD_HISTORY_WANG_COVERAGE';
   v_err_loc         VARCHAR2(100);
   v_err_number      NUMBER;
   v_err_msg         VARCHAR2(1500);


BEGIN

INSERT INTO STAGING.HISTORY_WANG_COVERAGE_RECORD
SELECT WCR.MAST_ID, WCR.POL_NUM, WCR.HIST_CD, WCR.SDS_LINE, WCR.ITEM_SEQ, WCR.REC_ID, WCR.COV_CODE, WCR.END_NUM, 
WCR.COV_PREM, DECODE(WCR.COV_LIMIT_EXCESS_SW,'Y',WCR.COV_LIMIT_EXCESS,WCR.COV_LIMIT) COV_LIMIT, WCR.COV_ED_DATE, WCR.COV_CLASS_CD, 
WCR.BOP_MEXT_SIGN_VAL, WCR.BOP_MEXT_GLASS, WCR.BOP_NY_MEXT_GLASS_1, WCR.BOP_NY_MEXT_GLASS_2, WCR.BOP_MEMPL_DISHON, WCR.NUM_RES_BY_FAM, 
WCR.COV_DED_TYPE, WCR.COV_DED_AMT, WCR.COV_END_TYPE, WCR.COV_RATE_IND, WCR.COV_RATE, WCR.NY_MAON_EXCESS, WCR.COV_PARM_1, WCR.COV_PARM_2, 
WCR.COV_PARM_3, WCR.COV_PARM_4, WCR.COV_PARM_5, WCR.COV_COIN_PCT, WCR.COV_COIN_AMT, WCR.COV_LIMIT_2, WCR.PREV_MCOV_PREM, 
WCR.COV_PREM_PRO_B, WCR.COV_PREM_PRO_A, WCR.COV_PRO_RATE_SW, WCR.COV_STAT_SWITCH, WCR.COV_RATE_SWITCH, WCR.COV_UPDATE_SWITCH, 
WCR.SDS_COVERAGE, WCR.REIN_TYPE_1, WCR.REIN_COMPANY_1, WCR.REIN_CONTRACT_1, WCR.REIN_AMT_1, WCR.REIN_CONTRACT_5_1, 
WCR.REIN_EXCESS_AMT_SW_1, WCR.REIN_EXCESS_AMT_1, WCR.REIN_PREM_1, WCR.REIN_PCT_1, WCR.REIN_COMM_1, WCR.REIN_TYPE_2, 
WCR.REIN_COMPANY_2, WCR.REIN_CONTRACT_2, WCR.REIN_AMT_2, WCR.REIN_CONTRACT_5_2, WCR.REIN_EXCESS_AMT_SW_2, WCR.REIN_EXCESS_AMT_2, 
WCR.REIN_PREM_2, WCR.REIN_PCT_2, WCR.REIN_COMM_2, WCR.REIN_TYPE_3, WCR.REIN_COMPANY_3, WCR.REIN_CONTRACT_3, WCR.REIN_AMT_3, 
WCR.REIN_CONTRACT_5_3, WCR.REIN_EXCESS_AMT_SW_3, WCR.REIN_EXCESS_AMT_3, WCR.REIN_PREM_3, WCR.REIN_PCT_3, WCR.REIN_COMM_3, 
WCR.REIN_TYPE_4, WCR.REIN_COMPANY_4, WCR.REIN_CONTRACT_4, WCR.REIN_AMT_4, WCR.REIN_CONTRACT_5_4,WCR.REIN_EXCESS_AMT_SW_4, 
WCR.REIN_EXCESS_AMT_4, WCR.REIN_PREM_4, WCR.REIN_PCT_4, WCR.REIN_COMM_4,WCR.REIN_TYPE_5, WCR.REIN_COMPANY_5, WCR.REIN_CONTRACT_5, 
WCR.REIN_AMT_5, WCR.REIN_CONTRACT_5_5, WCR.REIN_EXCESS_AMT_SW_5, WCR.REIN_EXCESS_AMT_5, WCR.REIN_PREM_5, WCR.REIN_PCT_5, 
WCR.REIN_COMM_5, WCR.REIN_PREV_PREM_1, WCR.REIN_PRM_PRO_B_1, WCR.REIN_PRM_PRO_A_1, WCR.REIN_PREV_PREM_2, WCR.REIN_PRM_PRO_B_2, 
WCR.REIN_PRM_PRO_A_2, WCR.REIN_PREV_PREM_3, WCR.REIN_PRM_PRO_B_3, WCR.REIN_PRM_PRO_A_3, WCR.REIN_PREV_PREM_4, WCR.REIN_PRM_PRO_B_4, 
WCR.REIN_PRM_PRO_A_4, WCR.REIN_PREV_PREM_5, WCR.REIN_PRM_PRO_B_5, WCR.REIN_PRM_PRO_A_5, WCR.REIN_ACTION_1, WCR.REIN_ACTION_2, 
WCR.REIN_ACTION_3, WCR.REIN_ACTION_4, WCR.REIN_ACTION_5, WCR.BFPB_MPA_OPTION, WCR.BFPB_MPA_MED_EXP, WCR.BFPB_MPA_WRK_LOSS, 
WCR.BFPB_MPA_FNRL_BEN, WCR.BFPB_MPA_ACC_DTH, WCR.BFPB_MPA_COMB, WCR.SURCHARGE_COMM, WCR.DISCOUNT_NH, WCR.MMV_BI_STAT_SW, WCR.BUR_CODE, 
WCR.END_CHNGE_SW, WCR.PRIOR_PREM, WCR.PRIOR_LIMIT, WCR.PRIOR_CHANGE_SW, WCR.COV_SDIP_PREM, WCR.COV_NY_BOP_RENT, WCR.COV_SDIP_FACTOR, 
WCR.COV_PREM_2, WCR.COV_COLL_WVR, WCR.ENDOR_DESCR_1, WCR.ENDOR_DESCR_2, WCR.ENDOR_DESCR_3, WCR.ENDOR_DESCR_4, WCR.ENDOR_DESCR_5, 
WCR.UNDL_POL_NUM_1, WCR.UNDL_COMP_1, WCR.UNDL_POL_NUM_2, WCR.UNDL_COMP_2, WCR.UNDL_POL_NUM_3, WCR.UNDL_COMP_3, WCR.UNDL_POL_NUM_4, 
WCR.UNDL_COMP_4, WCR.UNDL_POL_NUM_5, WCR.UNDL_COMP_5, WCR.BOP_MCOV_LIMIT_2, WCR.COV_LIMIT_EXCESS_SW, WCR.COV_LIMIT_EXCESS, WCR.RUN_DATE,
SYSDATE LOAD_DATE, history_coverage_seq.nextval HIST_COV_SEQ, WCR.REINS_RETAINED_AMT1,WCR.REINS_RETAINED_AMT2, WCR.REINS_RETAINED_AMT3, WCR.REINS_RETAINED_AMT4, WCR.REINS_RETAINED_AMT5
FROM STAGING.WF_WANG_COVERAGE_RECORD_EXT WCR;


COMMIT;


    EXCEPTION
        WHEN OTHERS THEN
        v_err_msg:=  v_procname||' FAILED:'||SQLCODE||':'||SQLERRM(SQLCODE);
        DBMS_OUTPUT.put_line(v_err_msg);  
     

 
END LOAD_HISTORY_WANG_COVERAGE;
/
