DROP MATERIALIZED VIEW BILLING.MBSI_REC_COMMIS
/

CREATE MATERIALIZED VIEW BILLING.MBSI_REC_COMMIS 
    (POLICY_NUMBER,PROCESS_DATE,POLICY_EFFECTIVE_DATE,COMMISSION_ENTITY_CODE,COMMISSION_ENTITY_TYPE,
     COMMISSION_AMOUNT)
TABLESPACE BILLING_DATA
PCTUSED    0
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOCACHE
NOLOGGING
NOCOMPRESS
BUILD IMMEDIATE
REFRESH COMPLETE ON DEMAND
WITH PRIMARY KEY
AS 
/* Formatted on 5/23/2019 2:50:23 PM (QP5 v5.326) */
  SELECT BA.POLICY_NUMBER,
         BA.PROCESS_DATE,
         BA.POLICY_EFFECTIVE_DATE,
         BA.AGENCY_NUMBER             COMMISSION_ENTITY_CODE,
         'BROKER'                     COMMISSION_ENTITY_TYPE,
         SUM (REC.COMMISSION_AMT)     COMMISSION_AMOUNT
    FROM BILLING.V_MBSI_PREM_RECEIVABLE  REC,
         BILLING.V_DAILY_BILLING_ACTIVITY BA
   WHERE REC.POLICY_NUMBER = BA.POLICY_NUMBER
GROUP BY BA.POLICY_NUMBER,
         BA.PROCESS_DATE,
         BA.POLICY_EFFECTIVE_DATE,
         BA.AGENCY_NUMBER
/


COMMENT ON MATERIALIZED VIEW BILLING.MBSI_REC_COMMIS IS 'snapshot table for snapshot BILLING.MBSI_REC_COMMIS'
/

CREATE UNIQUE INDEX BILLING.MBSI_REC_COMMIS_PK ON BILLING.MBSI_REC_COMMIS
(POLICY_NUMBER, PROCESS_DATE, POLICY_EFFECTIVE_DATE)
LOGGING
TABLESPACE BILLING_INDX001
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
/
